version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: update version"
    allow:
      - dependency-name: github.com/jackc/pgx/v5
      - dependency-name: github.com/lib/pq
      - dependency-name: github.com/prometheus/client_golang
      - dependency-name: gopkg.in/yaml.v3
      - dependency-name: github.com/avast/retry-go/v4
      - dependency-name: github.com/go-playground/errors
